feat: allow to use 'six.moves.collections_abc.Mapping' in 'client_options.from_dict()'
MaxxleLLC/google-api-python-client pull request #1
Opened 2020-05-07 18:28 UTC by paul1319

2020-05-12 15:01 UTC, IlyaFaer approved these changes
Looks like the things Bu Sun Kim was talking about.

2020-05-12 15:02 UTC, IlyaFaer commented
@paul1319, I think, we could add a unit test with other mapping object to be sure

2020-05-14 14:56 UTC, IlyaFaer approved these changes

2020-05-15 21:51 UTC, mf2199 requested changes

2020-05-15 21:51 UTC, mf2199 commented on googleapiclient/discovery.py
> +      options to set user options on the client. API endpoint should be set
`client` should be written in the same case, upper or lower. Also, `The API endpoint...`

2020-05-15 21:51 UTC, mf2199 commented on tests/test_discovery.py
> +        from collections import defaultdict
This can be placed at the top of the file, alongside the other imports.

2020-06-10 13:33 UTC, IlyaFaer reviewed
`The` should be added into both statements `API endpoint should be set through client_options` (though I don't think it actually should, @mf2199, WDYS?)

2020-06-12 14:26 UTC, mf2199 commented
> `The` should be added into both statements `API endpoint should be set through client_options` (though I don't think it actually should, @mf2199, WDYS?)

:+1: There are two such statements one of which contains the article; the second can be copied for the first.

2020-06-18 12:11 UTC, closed without merging